import Head from 'next/head'
import Image from 'next/image'
import cn from 'classnames'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

//componets 
import BackgroundImage from '../components/BackgroundImage/BackgroundImage.jsx'
import CenterHero from '../components/CenterHero/CenterHero.jsx'


import Orange from '../public/img/orange.jpg'
import AvoToast from '../public/img/avotoast.jpg'
import FitChick from '../public/img/fitchick3.jpg'
import Oats2 from '../public/img/oats2.jpg'
import TomatoCheese from '../public/img/tomatocheese.jpg'
import FruitBowl from '../public/img/fruitbowl.jpg'
import FoodTable from '../public/img/foodtable2.jpg'
import FruitJar from '../public/img/fruitjar.jpg'
import Chef1 from '../public/img/chef1.jpg'
import Chef2 from '../public/img/chef2.jpg'
import Chef3 from '../public/img/chef3.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        {/* <section className={styles.HeroWrapper}>
          <div className={cn(styles['HeroWrapperText'])}>
            <h1>Mealfit</h1>
            <h4>Eat Right for a balance life</h4>
          </div>
        </section> */}

        <BackgroundImage image={Orange}>
          <CenterHero title="Mealfit" subtitle="Eat Right for a balance life" />
        </BackgroundImage>

        <section className={styles.About}>

          <div className={styles.AboutText}>
            <div className={styles.AboutTextHeader}>
              <h2>About the <span>MealFit Story</span></h2>
            </div>
            <div className={styles.AboutTextContent}>
              <h4>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Vero, temporibus?</h4>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In ipsum odit, facere nihil aperiam enim. Dolor quisquam rem facere? Accusamus consequatur fugiat quibusdam! Beatae veniam id fugiat sapiente incidunt in ab omnis, saepe cumque vero assumenda doloremque reiciendis atque sunt.</p>
            </div>
          </div>
          
          <Image src={FitChick} alt="fit women eating healthy food" />

        </section>

        <section className={styles.Fine}>
          <div className={styles.FineText}>
            <h2>The Finest <span>Nature's Food</span></h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est sed laboriosam, consequuntur blanditiis voluptas praesentium repudiandae saepe natus itaque voluptates dolor repellat at? Non animi porro dignissimos possimus iusto in optio odio rem minus accusamus! Ullam officia fugit illo quis.</p>
          </div>

          <Image src={AvoToast} alt="avocados Toast"/>

          <div className={styles.FineSection}>
            <div className={styles.FineSectionItem}>
              <h4>Natural food</h4>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci harum sed culpa illum labore vitae voluptatum quis ducimus a minima.</p>
            </div>
            <div className={styles.FineSectionItem}>
              <h4>Natural food</h4>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci harum sed culpa illum labore vitae voluptatum quis ducimus a minima.</p>
            </div>
          </div>

        </section>

        <section className={`${styles.gridCol4} ${styles.GridArea2}`}>
          <div className={styles.PhiloSec}>
            <h4>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium, dolor!</h4>
          </div>
          <Image src={TomatoCheese} className={styles.PhilioImage1} alt="tomato cheese salad"/>
          <Image src={FruitBowl} className={styles.PhilioImage2} alt="Fruit Bowl yogurt"/>

          <div className={styles.PhiloText}>
            <div className={styles.secondaryHeading}>
              <h2>The Mealfit <span>Philosophy Here</span></h2>
            </div>
            
            <div className={styles.PhiloTextContainer}>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsam, repellat. Veritatis facilis aspernatur expedita ipsum porro mollitia vitae recusandae, doloribus sunt quis dicta magnam impedit, perspiciatis laudantium culpa eligendi nostrum repellat natus. Tempora, soluta libero?</p>
            </div>
            <div className={styles.PhiloTextContainer}>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsam, repellat. Veritatis facilis aspernatur expedita ipsum porro mollitia vitae recusandae, doloribus sunt quis dicta magnam impedit, perspiciatis laudantium culpa eligendi nostrum repellat natus. Tempora, soluta libero?</p>
            </div>
          </div>
        </section>

        <section className={`${styles.gridCol4} ${styles.GridArea1} ${styles.backing1}`}>
          <Image src={Oats2} className={`${styles.ImageCover} ${styles.goalsImage}`} alt="bowl in oats" />
          <div className={`${styles.secondaryHeading} ${styles.goalsTitle}`}>
              <h2>The Mealfit <span>Philosophy Here</span></h2>
          </div>
          <div className={`${styles.flex4} ${styles.goalsText}`}>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
          </div>
          
        </section>

        <section className={`${styles.flex1}`}>
          <div className={`${styles.flex1Text}`}>
            <h2 className={`${styles.secondaryHeading}`}>The Mealfit Team Here</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet assumenda expedita ab non porro alias ipsa laudantium maxime, excepturi, ipsum totam at neque rerum nobis pariatur nesciunt cupiditate minima tempore, ullam molestias dolore. In quisquam iure veniam, repudiandae laudantium temporibus?</p>
            
          </div>
          <div className={`${styles.Chefs}`}>
            <Image src={Chef1} className={`${styles.ImageCover}`} alt="picture of a chef" />
            <h4>Lorem ipsum dolor sit amet.</h4>
            <p>Lorem, ipsum dolor.</p>
          </div>
          <div className={`${styles.Chefs}`}>
            <Image src={Chef2} className={`${styles.ImageCover}`} alt="picture of a chef" />
            <h4>Lorem ipsum dolor sit amet.</h4>
            <p>Lorem, ipsum dolor.</p>
          </div>
          <div className={`${styles.Chefs}`}>
            <Image src={Chef3} className={`${styles.ImageCover}`} alt="picture of a chef" />
            <h4>Lorem ipsum dolor sit amet.</h4>
            <p>Lorem, ipsum dolor.</p>
          </div>
        </section>

        <section className={`${styles.gridCol4} ${styles.GridArea3}`}>
          <div className={`${styles.secondaryHeading}`}>
              <h2>Line Cook <span>Team Here</span></h2>
          </div>
          <div className={styles.Cooks}></div>
          {/* <Image src={Oats2} className={`${styles.ImageCover} ${styles.ChefOrange}` } alt="Glasses of fresh oranges"/> */}
          <div className={`${styles.flex} ${styles.Chef1}`}>
            <Image src={Chef2} className={`${styles.ImageCover} ${styles.rounded}`} alt="picture of a chef" />
            <div>
              <h5>Lorem, ipsum.</h5>
              <h4>Lorem ipsum dolor sit.</h4>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus quia mollitia distinctio non vero atque hic aspernatur accusantium, odit nemo architecto sequi reprehenderit enim quibusdam quod fuga ex alias ipsum.</p>
            </div>
          </div>
          <div className={`${styles.flex} ${styles.Chef2}`}>
            <Image src={Chef2} className={`${styles.ImageCover} ${styles.rounded}`} alt="picture of a chef" />
            <div>
              <h5>Lorem, ipsum.</h5>
              <h4>Lorem ipsum dolor sit.</h4>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus quia mollitia distinctio non vero atque hic aspernatur accusantium, odit nemo architecto sequi reprehenderit enim quibusdam quod fuga ex alias ipsum.</p>
            </div>
          </div>
        </section>

        <section>
          <div className={`${styles.secondaryHeading} ${styles.center}`}>
              <h2>Dont Panic <span>We're Organic</span></h2>
          </div>
          <div className={`${styles.FullGrid} ${styles.pt5}`}>
            <Image src={FoodTable} className={styles.ImageCover} alt="Table of food"/>
            <div className={`${styles.ColourPannel} ${styles.BgPrimary}`}>
              <div>
                <h4>Organic food</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus, consectetur impedit. Laborum at, assumenda dignissimos dolore natus deleniti sit cumque omnis doloribus tempora magni ea molestiae ipsum voluptatibus architecto molestias.</p>
              </div>
            </div>
            <div className={`${styles.ColourPannel} ${styles.BgSecondary}`}>
              <div>
                <h4>Organic food</h4>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus, consectetur impedit. Laborum at, assumenda dignissimos dolore natus deleniti sit cumque omnis doloribus tempora magni ea molestiae ipsum voluptatibus architecto molestias.</p>
              </div>
            </div>
          </div>
        </section>

        <section className={`${styles.pt5}`}>
          <div className={`${styles.secondaryHeading} ${styles.center}`}>
              <h2>Have to <span>Eat Right</span></h2>
          </div>
          <div className={`${styles.flex}`}>
            <div>
              <h4>Organic food</h4>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus, consectetur impedit. Laborum at, assumenda dignissimos dolore natus deleniti sit cumque omnis doloribus tempora magni ea molestiae ipsum voluptatibus architecto molestias.</p>
            </div>
            <div>
              <h4>Organic food</h4>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus, consectetur impedit. Laborum at, assumenda dignissimos dolore natus deleniti sit cumque omnis doloribus tempora magni ea molestiae ipsum voluptatibus architecto molestias.</p>
            </div>
            <div>
              <h4>Organic food</h4>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Delectus, consectetur impedit. Laborum at, assumenda dignissimos dolore natus deleniti sit cumque omnis doloribus tempora magni ea molestiae ipsum voluptatibus architecto molestias.</p>
            </div>
          </div>
          <div className={styles.FullGrid}>
            <Image src={FruitBowl} className={styles.ImageCover} alt="glass of oranges"/>
            <div className={`${styles.pannel}`}>
              <h4>Lorem ipsum dolor sit amet.</h4>
            </div>
            <Image src={FoodTable} className={styles.ImageCover} alt="glass of oranges" />
          </div>
        </section>

        <section className={styles.LowGrid}>
          <div className={styles.ColumnStack}>
            <Image src={FoodTable} className={styles.ImageCover} alt="glass of oranges"/>
            <div className={`${styles.LowGridPannel} `}>
              <h4>Lorem ipsum dolor sit amet.</h4>
            </div>
            <Image src={FruitBowl} className={styles.ImageCover} alt="glass of oranges" />
          </div>
          <div className={styles.LowGridText}>
            <div className={`${styles.secondaryHeading}`}>
                <h2>Fresh Food and <span>Good Moods</span></h2>
            </div>
            <div className={`${styles.flex4} ${styles.goalsText}`}>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
            <div className=''>
              <h5>Heading</h5>
              <h4>Lorem ipsum dolor sit amet.</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae voluptate molestiae laboriosam. Similique, error. Accusantium error explicabo quod veritatis atque.</p>
            </div>
          </div>
          </div>

        </section>    

      </main>
    </>
  )
}
